-- Optional: run in Supabase Dashboard → SQL Editor
-- Adds flattened survey columns for easier SQL export.
-- The app saves the full survey in post_survey (jsonb) even without these columns.

alter table public.simulation_sessions
  add column if not exists sq_q1_understanding_before integer,
  add column if not exists sq_q1_understanding_before_label text,
  add column if not exists sq_q2_understanding_after integer,
  add column if not exists sq_q2_understanding_after_label text,
  add column if not exists sq_q3_biggest_impact text,
  add column if not exists sq_q3_biggest_impact_label text,
  add column if not exists sq_q3_impact_other text,
  add column if not exists sq_q4_strategy_change text,
  add column if not exists sq_q4_strategy_change_label text,
  add column if not exists sq_q_end1_recommend text,
  add column if not exists sq_q_end1_recommend_label text,
  add column if not exists sq_q_end_ai_helpfulness text,
  add column if not exists sq_q_end_ai_helpfulness_label text,
  add column if not exists sq_q_end_ai_feedback text,
  add column if not exists sq_q_end2_suggestions text,
  add column if not exists sq_f1_heating_method text,
  add column if not exists sq_f1_heating_method_label text,
  add column if not exists sq_f1_method_other text,
  add column if not exists sq_f2_annual_heating_cost text,
  add column if not exists sq_f2_annual_heating_cost_label text,
  add column if not exists sq_f3_reduce_spending text,
  add column if not exists sq_f3_reduce_spending_label text,
  add column if not exists sq_f3_reduce_methods text,
  add column if not exists sq_f3_reduce_methods_labels text,
  add column if not exists sq_f4_cost_realism text,
  add column if not exists sq_f4_cost_realism_label text,
  add column if not exists sq_f5_subsidy_response text,
  add column if not exists sq_f5_subsidy_response_labels text,
  add column if not exists sq_f5_other text,
  add column if not exists sq_f6_realistic_part text,
  add column if not exists sq_f6_realistic_part_label text,
  add column if not exists sq_f7_unrealistic_part text,
  add column if not exists sq_f7_unrealistic_part_label text,
  add column if not exists sq_f8_policy_suggestion text,
  add column if not exists sq_n1_heating_method text,
  add column if not exists sq_n1_heating_method_label text,
  add column if not exists sq_n1_method_other text,
  add column if not exists sq_n2_concerns text,
  add column if not exists sq_n2_concerns_labels text,
  add column if not exists sq_n3_attitude text,
  add column if not exists sq_n3_attitude_label text,
  add column if not exists sq_n4_preferred_path text,
  add column if not exists sq_n4_preferred_path_label text,
  add column if not exists sq_farmer_interview_willing text,
  add column if not exists sq_farmer_interview_willing_label text,
  add column if not exists sq_farmer_interview_contact text;
